{{- if not .Values.controlPlane.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agency-os.fullname" . }}
  labels:
    {{- include "agency-os.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgres://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ include "agency-os.fullname" . }}-postgresql:5432/{{ .Values.postgresql.database }}"
  {{- end }}
  {{- range $k, $v := .Values.controlPlane.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agency-os.fullname" . }}-postgresql
  labels:
    {{- include "agency-os.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
{{- end }}