/**
 * Delivery loop contracts (v0.5.0): the closed pipeline
 *   spec → generate → write → test → diagnose → repair → review → commit.
 *
 * Code generation is pluggable:
 *  - TemplateCodegen: deterministic offline synthesis (used for CI/demo and
 *    air-gapped environments). It produces REAL executable files and REAL
 *    tests; nothing is simulated.
 *  - LlmCodegen: delegates to ModelRouter when MODEL_PROVIDER_API_KEY is set.
 */

export interface FileArtifact {
  path: string;
  content: string;
}

/** Structured, machine-checkable implementation spec attached to a task. */
export interface DeliverySpec {
  kind: "delivery";
  moduleName: string; // e.g. "calculator"
  description?: string;
  namespace?: string;
  /** PHASE 1.1: deterministic (default, offline) | agentic (LLM tool-loop) */
  mode?: "deterministic" | "agentic";
  /** PHASE B5: per-delivery performance budget (clamped by engine). */
  perfBudget?: { avgMsPerOp?: number; iterations?: number };
  /** PHASE B3: explicit engine override. */
  codegen?: "template" | "llm";
  ops: {
    name: string;
    arity: 2;
    /** Optional explicit test vectors [a, b, expected]. When omitted the
     *  engine picks canonical cases per op-name semantics (add/mul/sub) —
     *  or, for LLM codegen, semantics.examples drive generated tests. */
    cases?: [number, number, number][];
    /** PHASE B3: semantic description + examples drive LLM codegen & tests. */
    semantics?: {
      description: string;
      examples: { args: number[]; returns: number | string }[];
    };
  }[];
}

export interface GenerationResult {
  files: FileArtifact[];
  strategy: "template" | "llm";
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
  /** Aggregate content hash of generated files (evidence chain). */
  evidenceHash?: string;
  /** Agentic mode: auditable tool trajectory (Phase 1.1/1.7). */
  trajectory?: {
    mode: "deterministic" | "agentic";
    toolCalls: { tool: string; target: string; ok: boolean }[];
  };
}

export interface FailureInfo {
  testOutput: string;
  failingTest?: string;
  expected?: number;
  actual?: number;
  file?: string;
  /** assertion operator captured from the failure */
  operator?: string;
  /** numeric operands parsed from the failing test title (repair hints) */
  operandHintA?: number;
  operandHintB?: number;
}

export interface CodegenEngine {
  readonly strategy: "template" | "llm";
  generate(spec: DeliverySpec): Promise<GenerationResult>;
  /** Targeted repair after a failed test run. Returns patched files. */
  repair(
    spec: DeliverySpec,
    files: FileArtifact[],
    failure: FailureInfo
  ): Promise<{ files: FileArtifact[]; diagnosis: string; changed: boolean }>;
}

// ---------- shared code emitters (deterministic) ----------

export function emitModule(spec: DeliverySpec, opSymbol: Record<string, string>): FileArtifact {
  const fns = spec.ops
    .map((op) => {
      const sym = opSymbol[op.name] ?? "__OP__";
      return [
        `export function ${op.name}(a, b) {`,
        `  return a ${sym} b;`,
        `}`,
      ].join("\n");
    })
    .join("\n\n");
  const content = `// AUTO-GENERATED by Agency OS delivery loop\n` +
    `// module: ${spec.moduleName}\n\n${fns}\n`;
  return { path: `src/${spec.moduleName}.js`, content };
}

export function emitTests(spec: DeliverySpec, cases: Record<string, [number, number, number][]>): FileArtifact {
  const blocks = spec.ops
    .map((op) => {
      const list = cases[op.name];
      if (!list || list.length === 0) return "";
      return list
        .map((c) =>
          [
            `test('${op.name}(${c[0]}, ${c[1]}) === ${c[2]}', () => {`,
            `  assert.strictEqual(${op.name}(${c[0]}, ${c[1]}), ${c[2]});`,
            `});`,
          ].join("\n")
        )
        .join("\n\n");
    })
    .filter(Boolean)
    .join("\n\n");
  const content = `import { test } from 'node:test';\nimport assert from 'node:assert/strict';\n` +
    `import { ${spec.ops.map((o) => o.name).join(", ")} } from '../src/${spec.moduleName}.js';\n\n${blocks}\n`;
  return { path: `test/${spec.moduleName}.test.js`, content };
}

export function emitPackageJson(spec: DeliverySpec): FileArtifact {
  return {
    path: "package.json",
    content: JSON.stringify(
      {
        name: `${spec.namespace ?? "agencyos-demo"}-${spec.moduleName}`,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: { test: "node --test test/" },
      },
      null,
      2
    ) + "\n",
  };
}

/** Auto-generated operator documentation (master pipeline Phase 3.3). */
export function emitReadme(
  spec: DeliverySpec,
  cases: Record<string, [number, number, number][]>,
  opSymbol: Record<string, string>
): FileArtifact {
  const rows = spec.ops.map((op) => {
    const first = cases[op.name]?.[0];
    const example = first ? `\`${op.name}(${first[0]}, ${first[1]}) → ${first[2]}\`` : "—";
    return `| \`${op.name}\` | ${op.arity} | \`${opSymbol[op.name] ?? "?"}\` | ${example} |`;
  });
  const importNames = spec.ops.map((o) => o.name).join(", ");
  const desc = spec.description ? `\n> ${spec.description}\n` : "";
  const content =
    `# ${spec.moduleName}\n` +
    desc +
    `\nAuto-generated by the Agency OS delivery loop. Pure binary operators with\n` +
    `spec-driven test vectors; no I/O, no dynamic code execution.\n\n` +
    `## API\n\n| Op | Arity | Symbol | Example |\n|---|---|---|---|\n${rows.join("\n")}\n\n` +
    `## Usage\n\n\`\`\`js\nimport { ${importNames} } from './src/${spec.moduleName}.js';\n\`\`\`\n\n` +
    `## Quality\n\n- Tests: \`node --test\` (${spec.ops.reduce((n, o) => n + (cases[o.name]?.length ?? 0), 0)} vectors)\n` +
    `- Review gate: secrets / path-safety / debug-code — BLOCK on any finding\n`;
  return { path: "README.md", content };
}
