/**
 * Delivery loop contracts (v0.5.0): the closed pipeline
 *   spec → generate → write → test → diagnose → repair → review → commit.
 *
 * Code generation is pluggable:
 *  - TemplateCodegen: deterministic offline synthesis (used for CI/demo and
 *    air-gapped environments). It produces REAL executable files and REAL
 *    tests; nothing is simulated.
 *  - LlmCodegen: delegates to ModelRouter when MODEL_PROVIDER_API_KEY is set.
 */

export interface FileArtifact {
  path: string;
  content: string;
}

/** Structured, machine-checkable implementation spec attached to a task. */
export interface DeliverySpec {
  kind: "delivery";
  moduleName: string; // e.g. "calculator"
  namespace?: string;
  ops: { name: string; arity: 2 }[];
}

export interface GenerationResult {
  files: FileArtifact[];
  strategy: "template" | "llm";
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
}

export interface FailureInfo {
  testOutput: string;
  failingTest?: string;
  expected?: number;
  actual?: number;
  file?: string;
  /** assertion operator captured from the failure */
  operator?: string;
  /** numeric operands parsed from the failing test title (repair hints) */
  operandHintA?: number;
  operandHintB?: number;
}

export interface CodegenEngine {
  readonly strategy: "template" | "llm";
  generate(spec: DeliverySpec): Promise<GenerationResult>;
  /** Targeted repair after a failed test run. Returns patched files. */
  repair(
    spec: DeliverySpec,
    files: FileArtifact[],
    failure: FailureInfo
  ): Promise<{ files: FileArtifact[]; diagnosis: string; changed: boolean }>;
}

// ---------- shared code emitters (deterministic) ----------

export function emitModule(spec: DeliverySpec, opSymbol: Record<string, string>): FileArtifact {
  const fns = spec.ops
    .map((op) => {
      const sym = opSymbol[op.name] ?? "__OP__";
      return [
        `export function ${op.name}(a, b) {`,
        `  return a ${sym} b;`,
        `}`,
      ].join("\n");
    })
    .join("\n\n");
  const content = `// AUTO-GENERATED by Agency OS delivery loop\n` +
    `// module: ${spec.moduleName}\n\n${fns}\n`;
  return { path: `src/${spec.moduleName}.js`, content };
}

export function emitTests(spec: DeliverySpec, cases: Record<string, [number, number, number]>): FileArtifact {
  const blocks = spec.ops
    .map((op) => {
      const c = cases[op.name];
      if (!c) return "";
      return [
        `test('${op.name}(${c[0]}, ${c[1]}) === ${c[2]}', () => {`,
        `  assert.strictEqual(${op.name}(${c[0]}, ${c[1]}), ${c[2]});`,
        `});`,
      ].join("\n");
    })
    .filter(Boolean)
    .join("\n\n");
  const content = `import { test } from 'node:test';\nimport assert from 'node:assert/strict';\n` +
    `import { ${spec.ops.map((o) => o.name).join(", ")} } from '../src/${spec.moduleName}.js';\n\n${blocks}\n`;
  return { path: `test/${spec.moduleName}.test.js`, content };
}

export function emitPackageJson(spec: DeliverySpec): FileArtifact {
  return {
    path: "package.json",
    content: JSON.stringify(
      {
        name: `${spec.namespace ?? "agencyos-demo"}-${spec.moduleName}`,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: { test: "node --test test/" },
      },
      null,
      2
    ) + "\n",
  };
}
